WN2-39: utworzenie kanalu innego niz glowny
Finchsize/internship-2 pull request #13
Opened 2022-08-09 11:21 UTC by marcel-alefierowicz

2022-08-09 11:51 UTC, mejsiejdev commented on frontend/package.json
> -    "i18next-http-backend": "^1.4.1",
Czemu usunąłeś biblioteki od tłumaczeń?

2022-08-09 12:26 UTC, marcel-alefierowicz commented on frontend/package.json
> -    "i18next-http-backend": "^1.4.1",
Gdy przeszedłem na maina tych paczek nie było, po zainstalowaniu ich zmieniłem brancha i znowu ich nie ma.
Najprościej zapomniałem je dodać z powrotem :p

2022-08-10 10:07 UTC, mejsiejdev commented on frontend/src/components/Sidebar/Sidebar.tsx
> +      url: "/channels",
W ten sposób pobierasz wszystkie czaty, a nie tylko te do których użytkownik ma dostęp.

2022-08-10 11:04 UTC, marcel-alefierowicz commented on frontend/src/components/Sidebar/Sidebar.tsx
> +      url: "/channels",
myślę, że na to powininen być oddzielny task - przydzielenie dostępu poszczególnym użytkownikom. Natomiast na chwilę obecną nawet nie widać kto jest na czacie, a kto nie. Do ugadania na daily?

2022-08-10 12:54 UTC, mejsiejdev commented on frontend/src/components/Sidebar/Sidebar.tsx
> +      url: "/channels",
zapewne

2022-08-10 13:00 UTC, mejsiejdev requested changes

2022-08-10 13:00 UTC, mejsiejdev commented on frontend/src/components/Sidebar/Sidebar.tsx
> +      chats.push(res.data);
Nie tak aktualizuje się stan w React.
Jak chcesz dodać nowy czat do czatów to powinieneś to zrobić tak:
`setChats([...chats, res.data])`

2022-08-11 05:30 UTC, Finchsize commented on frontend/src/components/Sidebar/Sidebar.tsx
> +      url: "/channels",
Rzeczywiście słabo jest to opisane w docsach w swagerze: "Get available channels"
Nie pobierzesz wszystkich. Pobierzesz te, do których użytkownik z tokena ma dostęp, czyli: Jest wpisane w kanale na listę "owners" lub "members"

2022-08-11 05:34 UTC, Finchsize commented on frontend/src/components/Sidebar/Sidebar.tsx
> +              Main
Hmm, nie bardzo mi się to  podejście podoba. Wolałbym żeby `Main` został dodany do listy ręcznie i zrobić całość w `.map()`

2022-08-11 05:39 UTC, Finchsize commented on frontend/src/lib/parseJwt.ts
> +        return JSON.parse(window.atob(token.split(".")[1]));
Wstawiałem już to gdzieś, ale chyba się zgubiło więc napiszę jeszcze raz tutaj:
`This function is only provided for compatibility with legacy web platform APIs and should never be used in new code, because they use strings to represent binary data and predate the introduction of typed arrays in JavaScript. For code running using Node.js APIs, converting between base64-encoded strings and binary data should be performed using Buffer.from(str, 'base64') andbuf.toString('base64').`

2022-08-11 05:42 UTC, Finchsize commented on frontend/src/components/Sidebar/Sidebar.tsx
> +
Mało istotne: W wielu miejscach masz takie dziury z pustych linii, niby nieważne, bo nie wpływa na działanie apki, ale jednak jest to dziwne

2022-08-11 07:37 UTC, marcel-alefierowicz commented on frontend/src/components/Sidebar/Sidebar.tsx
> +              Main
kanał main jest z automatu w bazie, bo to kanał globalny o ID: 0, więc nie bardzo wiem jak zmapować ten kanał ;/

2022-08-11 07:41 UTC, marcel-alefierowicz commented on frontend/src/lib/parseJwt.ts
> +        return JSON.parse(window.atob(token.split(".")[1]));
odrazu mówię, że tego pliku nie tykam bo się boje panicznie, że coś zepsuję

2022-08-12 07:18 UTC, closed without merging