WN2-58: prettier & react-helmet
Finchsize/internship-2 pull request #31
Opened 2022-08-17 08:52 UTC by marcel-alefierowicz

2022-08-17 10:04 UTC, mejsiejdev commented
Według mnie wszystko tu wygląda dobrze

2022-08-18 07:52 UTC, Finchsize requested changes

2022-08-18 07:52 UTC, Finchsize commented on frontend/src/App.tsx
> +      </Helmet>
Oj nie tak. utwórz komponent `MetaTags` i wydziel to tam + dodaj translacje

2022-08-18 07:54 UTC, Finchsize commented on frontend/src/pages/register/register.tsx
> +        </Helmet>
Troszkę inaczej. Sparametryzuj komponent `MetaTags` i używaj go w innych komponentach

2022-08-18 09:38 UTC, Finchsize commented on frontend/src/components/MetaTags/MetaTags.tsx
> +export const MetaTags = (props: MetaTagsProps) => {
Zrób dekonstrukcję na `props` tutaj masz opis czym to jest:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment
A przykłady znajdziesz nawet w waszej apce

2022-08-18 09:40 UTC, Finchsize approved these changes
Mała poprawka i będzie ok

2022-08-18 09:52 UTC, merged